[tool.mypy]
disable_error_code = "annotation-unchecked"
enable_error_code = "ignore-without-code, redundant-self, truthy-iterable"
follow_imports = "silent"
check_untyped_defs = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
local_partial_types = true
no_implicit_optional = true
no_implicit_reexport = true
show_error_codes = true
strict_concatenate = false
strict_equality = true
warn_incomplete_stub = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.ruff]
lint.extend-select = [
    "I",      # Imports
    "SLF001", # Private member access
]

[tool.pytest.ini_options]
pythonpath = ['.']
asyncio_default_fixture_loop_scope = "session"
